monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.usb-ARTURIA_MiniFuse_1-00.HiFi__Line2__sink"
      }
      {
        node.name = "alsa_input.usb-ARTURIA_MiniFuse_1-00.HiFi__Line2__source"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]
